version: '3.9'

services:
  postgres:
    image: docker.io/postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mai_backend
  opensearch:
    image: docker.io/opensearchproject/opensearch:2.0.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9600:9600
  opensearch-dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:2.0.0
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
