version: '3.9'

services:
  api-server:
    build:
      context: ./
      dockerfile: ./deploy/docker/api-server.dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: "8080"
      POSTGRES: "postgres://postgres:pass@postgres:5432/mai_backend?sslmode=disable"
      OPENSEARCH_ADDRESSES: https://opensearch:9200
      OPENSEARCH_USERNAME: admin
      OPENSEARCH_PASSWORD: admin
  nginx:
    build:
      context: ./
      dockerfile: ./deploy/docker/ui-server.dockerfile
    environment:
      PORT: '80'
      API_SERVER_ADDR: 'http://api-server:8080'
    ports:
      - 80:80
  postgres:
    image: docker.io/postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mai_backend
  opensearch:
    image: docker.io/opensearchproject/opensearch:2.0.0
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9600:9600
  opensearch-dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:2.0.0
    restart: always
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
