// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/runtime.go

const (
	Version = "v0.10.2-0.20220512043615-f2e0bef7a803"           // Version of ent codegen.
	Sum     = "h1:hlVxT7O3OxI9uLvDIaIdNMCNaQ6aIspzdXzbnuJ1TXs=" // Sum of ent codegen.
)
