// Code generated by entc, DO NOT EDIT.

package userauth

const (
	// Label holds the string label denoting the userauth type in the database.
	Label = "user_auth"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// Table holds the table name of the userauth in the database.
	Table = "user_auths"
)

// Columns holds all SQL columns for userauth fields.
var Columns = []string{
	FieldID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
