// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/friendrequest"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/predicate"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/user"
)

// FriendRequestQuery is the builder for querying FriendRequest entities.
type FriendRequestQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FriendRequest
	// eager-loading edges.
	withFrom  *UserQuery
	withTo    *UserQuery
	withFKs   bool
	modifiers []func(*sql.Selector)
	loadTotal []func(context.Context, []*FriendRequest) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FriendRequestQuery builder.
func (frq *FriendRequestQuery) Where(ps ...predicate.FriendRequest) *FriendRequestQuery {
	frq.predicates = append(frq.predicates, ps...)
	return frq
}

// Limit adds a limit step to the query.
func (frq *FriendRequestQuery) Limit(limit int) *FriendRequestQuery {
	frq.limit = &limit
	return frq
}

// Offset adds an offset step to the query.
func (frq *FriendRequestQuery) Offset(offset int) *FriendRequestQuery {
	frq.offset = &offset
	return frq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (frq *FriendRequestQuery) Unique(unique bool) *FriendRequestQuery {
	frq.unique = &unique
	return frq
}

// Order adds an order step to the query.
func (frq *FriendRequestQuery) Order(o ...OrderFunc) *FriendRequestQuery {
	frq.order = append(frq.order, o...)
	return frq
}

// QueryFrom chains the current query on the "from" edge.
func (frq *FriendRequestQuery) QueryFrom() *UserQuery {
	query := &UserQuery{config: frq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(friendrequest.Table, friendrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, friendrequest.FromTable, friendrequest.FromColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTo chains the current query on the "to" edge.
func (frq *FriendRequestQuery) QueryTo() *UserQuery {
	query := &UserQuery{config: frq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := frq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(friendrequest.Table, friendrequest.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, friendrequest.ToTable, friendrequest.ToColumn),
		)
		fromU = sqlgraph.SetNeighbors(frq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FriendRequest entity from the query.
// Returns a *NotFoundError when no FriendRequest was found.
func (frq *FriendRequestQuery) First(ctx context.Context) (*FriendRequest, error) {
	nodes, err := frq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{friendrequest.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (frq *FriendRequestQuery) FirstX(ctx context.Context) *FriendRequest {
	node, err := frq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FriendRequest ID from the query.
// Returns a *NotFoundError when no FriendRequest ID was found.
func (frq *FriendRequestQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{friendrequest.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (frq *FriendRequestQuery) FirstIDX(ctx context.Context) int {
	id, err := frq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FriendRequest entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FriendRequest entity is found.
// Returns a *NotFoundError when no FriendRequest entities are found.
func (frq *FriendRequestQuery) Only(ctx context.Context) (*FriendRequest, error) {
	nodes, err := frq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{friendrequest.Label}
	default:
		return nil, &NotSingularError{friendrequest.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (frq *FriendRequestQuery) OnlyX(ctx context.Context) *FriendRequest {
	node, err := frq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FriendRequest ID in the query.
// Returns a *NotSingularError when more than one FriendRequest ID is found.
// Returns a *NotFoundError when no entities are found.
func (frq *FriendRequestQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = frq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{friendrequest.Label}
	default:
		err = &NotSingularError{friendrequest.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (frq *FriendRequestQuery) OnlyIDX(ctx context.Context) int {
	id, err := frq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FriendRequests.
func (frq *FriendRequestQuery) All(ctx context.Context) ([]*FriendRequest, error) {
	if err := frq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return frq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (frq *FriendRequestQuery) AllX(ctx context.Context) []*FriendRequest {
	nodes, err := frq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FriendRequest IDs.
func (frq *FriendRequestQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := frq.Select(friendrequest.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (frq *FriendRequestQuery) IDsX(ctx context.Context) []int {
	ids, err := frq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (frq *FriendRequestQuery) Count(ctx context.Context) (int, error) {
	if err := frq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return frq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (frq *FriendRequestQuery) CountX(ctx context.Context) int {
	count, err := frq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (frq *FriendRequestQuery) Exist(ctx context.Context) (bool, error) {
	if err := frq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return frq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (frq *FriendRequestQuery) ExistX(ctx context.Context) bool {
	exist, err := frq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FriendRequestQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (frq *FriendRequestQuery) Clone() *FriendRequestQuery {
	if frq == nil {
		return nil
	}
	return &FriendRequestQuery{
		config:     frq.config,
		limit:      frq.limit,
		offset:     frq.offset,
		order:      append([]OrderFunc{}, frq.order...),
		predicates: append([]predicate.FriendRequest{}, frq.predicates...),
		withFrom:   frq.withFrom.Clone(),
		withTo:     frq.withTo.Clone(),
		// clone intermediate query.
		sql:    frq.sql.Clone(),
		path:   frq.path,
		unique: frq.unique,
	}
}

// WithFrom tells the query-builder to eager-load the nodes that are connected to
// the "from" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FriendRequestQuery) WithFrom(opts ...func(*UserQuery)) *FriendRequestQuery {
	query := &UserQuery{config: frq.config}
	for _, opt := range opts {
		opt(query)
	}
	frq.withFrom = query
	return frq
}

// WithTo tells the query-builder to eager-load the nodes that are connected to
// the "to" edge. The optional arguments are used to configure the query builder of the edge.
func (frq *FriendRequestQuery) WithTo(opts ...func(*UserQuery)) *FriendRequestQuery {
	query := &UserQuery{config: frq.config}
	for _, opt := range opts {
		opt(query)
	}
	frq.withTo = query
	return frq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (frq *FriendRequestQuery) GroupBy(field string, fields ...string) *FriendRequestGroupBy {
	grbuild := &FriendRequestGroupBy{config: frq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := frq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return frq.sqlQuery(ctx), nil
	}
	grbuild.label = friendrequest.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (frq *FriendRequestQuery) Select(fields ...string) *FriendRequestSelect {
	frq.fields = append(frq.fields, fields...)
	selbuild := &FriendRequestSelect{FriendRequestQuery: frq}
	selbuild.label = friendrequest.Label
	selbuild.flds, selbuild.scan = &frq.fields, selbuild.Scan
	return selbuild
}

func (frq *FriendRequestQuery) prepareQuery(ctx context.Context) error {
	for _, f := range frq.fields {
		if !friendrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if frq.path != nil {
		prev, err := frq.path(ctx)
		if err != nil {
			return err
		}
		frq.sql = prev
	}
	return nil
}

func (frq *FriendRequestQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*FriendRequest, error) {
	var (
		nodes       = []*FriendRequest{}
		withFKs     = frq.withFKs
		_spec       = frq.querySpec()
		loadedTypes = [2]bool{
			frq.withFrom != nil,
			frq.withTo != nil,
		}
	)
	if frq.withFrom != nil || frq.withTo != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, friendrequest.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*FriendRequest).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &FriendRequest{config: frq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(frq.modifiers) > 0 {
		_spec.Modifiers = frq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, frq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := frq.withFrom; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*FriendRequest)
		for i := range nodes {
			if nodes[i].friend_request_from == nil {
				continue
			}
			fk := *nodes[i].friend_request_from
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "friend_request_from" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.From = n
			}
		}
	}

	if query := frq.withTo; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*FriendRequest)
		for i := range nodes {
			if nodes[i].friend_request_to == nil {
				continue
			}
			fk := *nodes[i].friend_request_to
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "friend_request_to" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.To = n
			}
		}
	}

	for i := range frq.loadTotal {
		if err := frq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (frq *FriendRequestQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := frq.querySpec()
	if len(frq.modifiers) > 0 {
		_spec.Modifiers = frq.modifiers
	}
	_spec.Node.Columns = frq.fields
	if len(frq.fields) > 0 {
		_spec.Unique = frq.unique != nil && *frq.unique
	}
	return sqlgraph.CountNodes(ctx, frq.driver, _spec)
}

func (frq *FriendRequestQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := frq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (frq *FriendRequestQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   friendrequest.Table,
			Columns: friendrequest.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: friendrequest.FieldID,
			},
		},
		From:   frq.sql,
		Unique: true,
	}
	if unique := frq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := frq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendrequest.FieldID)
		for i := range fields {
			if fields[i] != friendrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := frq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := frq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := frq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := frq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (frq *FriendRequestQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(frq.driver.Dialect())
	t1 := builder.Table(friendrequest.Table)
	columns := frq.fields
	if len(columns) == 0 {
		columns = friendrequest.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if frq.sql != nil {
		selector = frq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if frq.unique != nil && *frq.unique {
		selector.Distinct()
	}
	for _, p := range frq.predicates {
		p(selector)
	}
	for _, p := range frq.order {
		p(selector)
	}
	if offset := frq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := frq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FriendRequestGroupBy is the group-by builder for FriendRequest entities.
type FriendRequestGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (frgb *FriendRequestGroupBy) Aggregate(fns ...AggregateFunc) *FriendRequestGroupBy {
	frgb.fns = append(frgb.fns, fns...)
	return frgb
}

// Scan applies the group-by query and scans the result into the given value.
func (frgb *FriendRequestGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := frgb.path(ctx)
	if err != nil {
		return err
	}
	frgb.sql = query
	return frgb.sqlScan(ctx, v)
}

func (frgb *FriendRequestGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range frgb.fields {
		if !friendrequest.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := frgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := frgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (frgb *FriendRequestGroupBy) sqlQuery() *sql.Selector {
	selector := frgb.sql.Select()
	aggregation := make([]string, 0, len(frgb.fns))
	for _, fn := range frgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(frgb.fields)+len(frgb.fns))
		for _, f := range frgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(frgb.fields...)...)
}

// FriendRequestSelect is the builder for selecting fields of FriendRequest entities.
type FriendRequestSelect struct {
	*FriendRequestQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (frs *FriendRequestSelect) Scan(ctx context.Context, v interface{}) error {
	if err := frs.prepareQuery(ctx); err != nil {
		return err
	}
	frs.sql = frs.FriendRequestQuery.sqlQuery(ctx)
	return frs.sqlScan(ctx, v)
}

func (frs *FriendRequestSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := frs.sql.Query()
	if err := frs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
