// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (u *User) Friends(ctx context.Context) ([]*User, error) {
	result, err := u.Edges.FriendsOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryFriends().All(ctx)
	}
	return result, err
}
