// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/predicate"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/userauth"
)

// UserAuthQuery is the builder for querying UserAuth entities.
type UserAuthQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.UserAuth
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*UserAuth) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UserAuthQuery builder.
func (uaq *UserAuthQuery) Where(ps ...predicate.UserAuth) *UserAuthQuery {
	uaq.predicates = append(uaq.predicates, ps...)
	return uaq
}

// Limit adds a limit step to the query.
func (uaq *UserAuthQuery) Limit(limit int) *UserAuthQuery {
	uaq.limit = &limit
	return uaq
}

// Offset adds an offset step to the query.
func (uaq *UserAuthQuery) Offset(offset int) *UserAuthQuery {
	uaq.offset = &offset
	return uaq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (uaq *UserAuthQuery) Unique(unique bool) *UserAuthQuery {
	uaq.unique = &unique
	return uaq
}

// Order adds an order step to the query.
func (uaq *UserAuthQuery) Order(o ...OrderFunc) *UserAuthQuery {
	uaq.order = append(uaq.order, o...)
	return uaq
}

// First returns the first UserAuth entity from the query.
// Returns a *NotFoundError when no UserAuth was found.
func (uaq *UserAuthQuery) First(ctx context.Context) (*UserAuth, error) {
	nodes, err := uaq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{userauth.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (uaq *UserAuthQuery) FirstX(ctx context.Context) *UserAuth {
	node, err := uaq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UserAuth ID from the query.
// Returns a *NotFoundError when no UserAuth ID was found.
func (uaq *UserAuthQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uaq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{userauth.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (uaq *UserAuthQuery) FirstIDX(ctx context.Context) int {
	id, err := uaq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UserAuth entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UserAuth entity is found.
// Returns a *NotFoundError when no UserAuth entities are found.
func (uaq *UserAuthQuery) Only(ctx context.Context) (*UserAuth, error) {
	nodes, err := uaq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{userauth.Label}
	default:
		return nil, &NotSingularError{userauth.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (uaq *UserAuthQuery) OnlyX(ctx context.Context) *UserAuth {
	node, err := uaq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UserAuth ID in the query.
// Returns a *NotSingularError when more than one UserAuth ID is found.
// Returns a *NotFoundError when no entities are found.
func (uaq *UserAuthQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = uaq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{userauth.Label}
	default:
		err = &NotSingularError{userauth.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (uaq *UserAuthQuery) OnlyIDX(ctx context.Context) int {
	id, err := uaq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UserAuths.
func (uaq *UserAuthQuery) All(ctx context.Context) ([]*UserAuth, error) {
	if err := uaq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return uaq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (uaq *UserAuthQuery) AllX(ctx context.Context) []*UserAuth {
	nodes, err := uaq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UserAuth IDs.
func (uaq *UserAuthQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := uaq.Select(userauth.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (uaq *UserAuthQuery) IDsX(ctx context.Context) []int {
	ids, err := uaq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (uaq *UserAuthQuery) Count(ctx context.Context) (int, error) {
	if err := uaq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return uaq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (uaq *UserAuthQuery) CountX(ctx context.Context) int {
	count, err := uaq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (uaq *UserAuthQuery) Exist(ctx context.Context) (bool, error) {
	if err := uaq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return uaq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (uaq *UserAuthQuery) ExistX(ctx context.Context) bool {
	exist, err := uaq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UserAuthQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (uaq *UserAuthQuery) Clone() *UserAuthQuery {
	if uaq == nil {
		return nil
	}
	return &UserAuthQuery{
		config:     uaq.config,
		limit:      uaq.limit,
		offset:     uaq.offset,
		order:      append([]OrderFunc{}, uaq.order...),
		predicates: append([]predicate.UserAuth{}, uaq.predicates...),
		// clone intermediate query.
		sql:    uaq.sql.Clone(),
		path:   uaq.path,
		unique: uaq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
func (uaq *UserAuthQuery) GroupBy(field string, fields ...string) *UserAuthGroupBy {
	grbuild := &UserAuthGroupBy{config: uaq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := uaq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return uaq.sqlQuery(ctx), nil
	}
	grbuild.label = userauth.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
func (uaq *UserAuthQuery) Select(fields ...string) *UserAuthSelect {
	uaq.fields = append(uaq.fields, fields...)
	selbuild := &UserAuthSelect{UserAuthQuery: uaq}
	selbuild.label = userauth.Label
	selbuild.flds, selbuild.scan = &uaq.fields, selbuild.Scan
	return selbuild
}

func (uaq *UserAuthQuery) prepareQuery(ctx context.Context) error {
	for _, f := range uaq.fields {
		if !userauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if uaq.path != nil {
		prev, err := uaq.path(ctx)
		if err != nil {
			return err
		}
		uaq.sql = prev
	}
	return nil
}

func (uaq *UserAuthQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UserAuth, error) {
	var (
		nodes = []*UserAuth{}
		_spec = uaq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*UserAuth).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &UserAuth{config: uaq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(uaq.modifiers) > 0 {
		_spec.Modifiers = uaq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, uaq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	for i := range uaq.loadTotal {
		if err := uaq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (uaq *UserAuthQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := uaq.querySpec()
	if len(uaq.modifiers) > 0 {
		_spec.Modifiers = uaq.modifiers
	}
	_spec.Node.Columns = uaq.fields
	if len(uaq.fields) > 0 {
		_spec.Unique = uaq.unique != nil && *uaq.unique
	}
	return sqlgraph.CountNodes(ctx, uaq.driver, _spec)
}

func (uaq *UserAuthQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := uaq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (uaq *UserAuthQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   userauth.Table,
			Columns: userauth.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: userauth.FieldID,
			},
		},
		From:   uaq.sql,
		Unique: true,
	}
	if unique := uaq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := uaq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, userauth.FieldID)
		for i := range fields {
			if fields[i] != userauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := uaq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := uaq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := uaq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := uaq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (uaq *UserAuthQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(uaq.driver.Dialect())
	t1 := builder.Table(userauth.Table)
	columns := uaq.fields
	if len(columns) == 0 {
		columns = userauth.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if uaq.sql != nil {
		selector = uaq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if uaq.unique != nil && *uaq.unique {
		selector.Distinct()
	}
	for _, p := range uaq.predicates {
		p(selector)
	}
	for _, p := range uaq.order {
		p(selector)
	}
	if offset := uaq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := uaq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UserAuthGroupBy is the group-by builder for UserAuth entities.
type UserAuthGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uagb *UserAuthGroupBy) Aggregate(fns ...AggregateFunc) *UserAuthGroupBy {
	uagb.fns = append(uagb.fns, fns...)
	return uagb
}

// Scan applies the group-by query and scans the result into the given value.
func (uagb *UserAuthGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := uagb.path(ctx)
	if err != nil {
		return err
	}
	uagb.sql = query
	return uagb.sqlScan(ctx, v)
}

func (uagb *UserAuthGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range uagb.fields {
		if !userauth.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := uagb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uagb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (uagb *UserAuthGroupBy) sqlQuery() *sql.Selector {
	selector := uagb.sql.Select()
	aggregation := make([]string, 0, len(uagb.fns))
	for _, fn := range uagb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(uagb.fields)+len(uagb.fns))
		for _, f := range uagb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(uagb.fields...)...)
}

// UserAuthSelect is the builder for selecting fields of UserAuth entities.
type UserAuthSelect struct {
	*UserAuthQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (uas *UserAuthSelect) Scan(ctx context.Context, v interface{}) error {
	if err := uas.prepareQuery(ctx); err != nil {
		return err
	}
	uas.sql = uas.UserAuthQuery.sqlQuery(ctx)
	return uas.sqlScan(ctx, v)
}

func (uas *UserAuthSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := uas.sql.Query()
	if err := uas.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
