// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/mayamika/2022-mai-backend-a-chakiryan/api-server/internal/ent/userauth"
)

// UserAuth is the model entity for the UserAuth schema.
type UserAuth struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserAuth) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case userauth.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type UserAuth", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserAuth fields.
func (ua *UserAuth) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case userauth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ua.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this UserAuth.
// Note that you need to call UserAuth.Unwrap() before calling this method if this UserAuth
// was returned from a transaction, and the transaction was committed or rolled back.
func (ua *UserAuth) Update() *UserAuthUpdateOne {
	return (&UserAuthClient{config: ua.config}).UpdateOne(ua)
}

// Unwrap unwraps the UserAuth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ua *UserAuth) Unwrap() *UserAuth {
	tx, ok := ua.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserAuth is not a transactional entity")
	}
	ua.config.driver = tx.drv
	return ua
}

// String implements the fmt.Stringer.
func (ua *UserAuth) String() string {
	var builder strings.Builder
	builder.WriteString("UserAuth(")
	builder.WriteString(fmt.Sprintf("id=%v", ua.ID))
	builder.WriteByte(')')
	return builder.String()
}

// UserAuths is a parsable slice of UserAuth.
type UserAuths []*UserAuth

func (ua UserAuths) config(cfg config) {
	for _i := range ua {
		ua[_i].config = cfg
	}
}
