// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// FriendRequest is the predicate function for friendrequest builders.
type FriendRequest func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
