name: Go

on:
  push:
    paths:
      - "**.go"
# jobs:
# golangci-lint currently doesn't support go 1.18
# https://github.com/golangci/golangci-lint/pull/2438
#
# lint:
#   name: Lint
#   runs-on: ubuntu-latest
#   steps:
#     - uses: actions/checkout@v2
#     - uses: golangci/golangci-lint-action@v2
#       with:
#         version: latest
